### PR TITLE
chore: upgrade install-pkg

### PR DESCRIPTION
**Pull request by benmccann**
### ❓ Type of change

- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

Upgrades a dependency to the latest version

### 📝 Checklist

- [ ] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by thetutlage** [comment]
The newer version of `@antfu/install-pkg` is still broken. Did not have time to look into it why. But I will see and replace it with a custom implementation soon

**Comment by benmccann** [comment]
My bad for not running the tests. I thought it'd be simple and unlikely to fail

>  Assertion Error: Expected log messages to match /pnpm install.*inexistent exited/
Compared values have no visual difference.
   at Object.executor tests\commands\add.spec.ts:263

**Comment by benmccann** [comment]
Hmm. This seems to be related to `@antfu/install-pkg` moving to `tinyexec`.

Here's what is in the log messages:
```
[
   {
      "message":"[ blue(info) ] Installing the package using the following command : grey(pnpm add file:///tmp/dwwibyshpirrbghjzq0p8m51/node_modules/inexistent)",
      "stream":"stdout"
   },
   {
      "message":"[ cyan(wait) ] installing green(file:///tmp/dwwibyshpirrbghjzq0p8m51/node_modules/inexistent) using grey(pnpm) .  ",
      "stream":"stdout"
   },
   {
      "message":"[ cyan(wait) ] installing green(file:///tmp/dwwibyshpirrbghjzq0p8m51/node_modules/inexistent) using grey(pnpm) .  ",
      "stream":"stdout"
   },
   {
      "message":"[ cyan(wait) ] installing green(file:///tmp/dwwibyshpirrbghjzq0p8m51/node_modules/inexistent) using grey(pnpm) .. ",
      "stream":"stdout"
   },
   {
      "message":"[ cyan(wait) ] installing green(file:///tmp/dwwibyshpirrbghjzq0p8m51/node_modules/inexistent) using grey(pnpm) ...",
      "stream":"stdout"
   },
   {
      "message":"[ cyan(wait) ] installing green(file:///tmp/dwwibyshpirrbghjzq0p8m51/node_modules/inexistent) using grey(pnpm)  ..",
      "stream":"stdout"
   },
   {
      "message":"[ cyan(wait) ] installing green(file:///tmp/dwwibyshpirrbghjzq0p8m51/node_modules/inexistent) using grey(pnpm)   .",
      "stream":"stdout"
   },
   {
      "message":"[ cyan(wait) ] installing green(file:///tmp/dwwibyshpirrbghjzq0p8m51/node_modules/inexistent) using grey(pnpm)    ",
      "stream":"stdout"
   },
   {
      "message":"[ cyan(wait) ] installing green(file:///tmp/dwwibyshpirrbghjzq0p8m51/node_modules/inexistent) using grey(pnpm) .  ",
      "stream":"stdout"
   },
   {
      "message":"[ cyan(wait) ] package installed successfully ...",
      "stream":"stdout"
   },
   {
      "message":"[ red(error) ] Cannot find module \"file:///tmp/dwwibyshpirrbghjzq0p8m51/node_modules/inexistent\". Make sure to install it",
      "stream":"stderr"
   },
   {
      "message":"[ red(error) ] Unable to configure green(file:///tmp/dwwibyshpirrbghjzq0p8m51/node_modules/inexistent)",
      "stream":"stderr"
   }
]
```

And here's what was in the log messages before the upgrade:
```
[
   {
      "message":"[ blue(info) ] Installing the package using the following command : grey(pnpm add file:///tmp/tdrmo30es4po5jm4wxuy7bmx/node_modules/inexistent)",
      "stream":"stdout"
   },
   {
      "message":"[ cyan(wait) ] installing green(file:///tmp/tdrmo30es4po5jm4wxuy7bmx/node_modules/inexistent) using grey(pnpm) .  ",
      "stream":"stdout"
   },
   {
      "message":"[ cyan(wait) ] installing green(file:///tmp/tdrmo30es4po5jm4wxuy7bmx/node_modules/inexistent) using grey(pnpm) .  ",
      "stream":"stdout"
   },
   {
      "message":"[ cyan(wait) ] installing green(file:///tmp/tdrmo30es4po5jm4wxuy7bmx/node_modules/inexistent) using grey(pnpm) .. ",
      "stream":"stdout"
   },
   {
      "message":"[ cyan(wait) ] installing green(file:///tmp/tdrmo30es4po5jm4wxuy7bmx/node_modules/inexistent) using grey(pnpm) ...",
      "stream":"stdout"
   },
   {
      "message":"[ cyan(wait) ] installing green(file:///tmp/tdrmo30es4po5jm4wxuy7bmx/node_modules/inexistent) using grey(pnpm)  ..",
      "stream":"stdout"
   },
   {
      "message":"[ cyan(wait) ] installing green(file:///tmp/tdrmo30es4po5jm4wxuy7bmx/node_modules/inexistent) using grey(pnpm)   .",
      "stream":"stdout"
   },
   {
      "message":"[ cyan(wait) ] installing green(file:///tmp/tdrmo30es4po5jm4wxuy7bmx/node_modules/inexistent) using grey(pnpm)    ",
      "stream":"stdout"
   },
   {
      "message":"[ cyan(wait) ] installing green(file:///tmp/tdrmo30es4po5jm4wxuy7bmx/node_modules/inexistent) using grey(pnpm) .  ",
      "stream":"stdout"
   },
   {
      "message":"[ cyan(wait) ] unable to install the package ...",
      "stream":"stdout"
   },
   {
      "message":"[ red(error) ] pnpm install file:///tmp/tdrmo30es4po5jm4wxuy7bmx/node_modules/inexistent exited with a status of 1.\n      red(    at normalizeResult (node_modules/@jsdevtools/ez-spawn/lib/normalize-result.js:31:11))\n      red(    at ChildProcess.<anonymous> (node_modules/@jsdevtools/ez-spawn/lib/async.js:79:19))\n      red(    at ChildProcess.emit (node:events:519:28))\n      red(    at ChildProcess.emit (node:domain:488:12))\n      red(    at ChildProcess._handle.onexit (node:internal/child_process:294:12))",
      "stream":"stderr"
   }
]
```

**Comment by benmccann** [comment]
I filed https://github.com/tinylibs/tinyexec/issues/32 to address this upstream as it seems I inadvertently broke `install-pkg`. I will close this PR for now and we can look at upgrading it again after fixing it upstream shortly

**Pull request closed without merging**
