### PR TITLE
feat(log): add log service so you can log things to console and syslog

### PR DESCRIPTION
**Pull request by goschevski**
Log module should be used to log important things to console (using `cat-log`) and `syslog` (using `ain2` module from npm).

I can probably improve it, but I think this is enough for the first iteration.
Would need to propagate this module in other modules (instead of loading `cat-log` everywhere, we should load Log -> Helpers, Route, Server).

### CODE REVIEW

**Comment by goschevski** [comment]
I just saw this https://github.com/adonisjs/adonis-framework/issues/52

Anyway, I think adonis should have predefined Log component. That's something that's every node app needs to have.

**Comment by thetutlage** [comment]
@goschevski I'll keep this PR open and will clear my intentions first on what all I need from a logging component.

**Comment by goschevski** [comment]
@thetutlage sure thing! I should have asked you guys first on gitter what do you think. :)

**Comment by RomainLanz** [comment]
Maybe we should hold off this for the moment and create a discussion in the [adonis-discussion](https://github.com/adonisjs/discussion) repository?

**Comment by thetutlage** [comment]
Closing since AdonisJs has different plans, I will create a dicussion for same

**Pull request closed without merging**
