### PR TITLE
add back base64 helpers

### PR DESCRIPTION
**Pull request by RomainLanz**

### CODE REVIEW

**Comment by thetutlage** [comment]
I took them off intentionally, may be someone can add it themselves inside `bootstrap/start.js` file.

**Comment by RomainLanz** [comment]
You don't think that we will use it in the core?

**Comment by thetutlage** [comment]
I do not think so, doing a `base64` is pretty simple and nodejs itself has support for it. So adding one liners to be core will not help much.

May be we can a snippets page on Adonis website, where we can post these methods on how to do x thing in Adonis.

**Comment by RomainLanz** [comment]
:+1:

**Pull request closed without merging**
