### PR TITLE
feature-collection-and-member-routes

### PR DESCRIPTION
**Pull request by chukitow**
Hi,

I would like to add this new feature based on [Rails Routing](http://guides.rubyonrails.org/routing.html#adding-more-restful-actions). This feature allows to create more RESTful Actions.

Let me know if you like it :smile:

### CODE REVIEW

**Comment by thetutlage** [comment]
I am not a big fan of configuring things with this JSON'ish style. The API needs to be fluent. Something like

```javascript
Route.resource().addMember('completed') // defaults to GET,HEAD
// or
Route.resource().addMember('completed').verb('POST')
```

I am not 100% sure with the naming conventions, may be have to put some thoughts into it. 

Also there needs to be some tests for middleware to see whether adding `middleware` assigned to the resource applies to these member methods or not.

**Comment by chukitow** [comment]
I would add some test  for middleware.

What do you think about this naming convention?

```javascript
Route.resource()
  .addMember('completed')
  .addMember('mark_as_completed', 'POST')
```

**Comment by thetutlage** [comment]
Yes that looks better, `addMember` makes it more readable than `member`. As it is explicit that one is trying to add a new member to the existing resource

:+1:

**Comment by thetutlage** [comment]
And couple of things you need to take care of is

1. Adding a middleware to the resource, should be assigned to these new members.
2. using `as` method on resource, i should be able to give a new to new members.

**Comment by chukitow** [comment]
Currently is not possible to assign middlewares to a resource, isn't it?

`Route.resource(...).middlewares is not a function`

**Comment by thetutlage** [comment]
Yes it's my bad, i decided to make use of `group` when assigning middleware to the resource.

**Comment by chukitow** [comment]
I just updated the feature following the name convention that you suggested.

This feature only extend the capabilities of creating a resource, adding `middlewares` o changing route name using `as` method could be in other feature.

**Comment by chukitow** [comment]
so, what do you think @thetutlage  ?

**Comment by thetutlage** [comment]
@chukitow I am waiting for you to implement tests for named (`as`) routes. Ideally all this needs to be one feature.

**Comment by chukitow** [comment]
Sorry for the delay @thetutlage, I have updated the branch adding tests for named routes using the `as` method.

**Comment by thetutlage** [comment]
Thanks @chukitow . I have made some improvements to the PR before merge. If you want, you have a look at the current develop branch.

**Pull request merged**
