### PR TITLE
TS support in routes

### PR DESCRIPTION
**Pull request by anurbol**
peek 2018-06-03 15-14

There are way too many files "changed" because of following chronology:
1. You made "typescript" branch
2. Few commits was made to "develop" branch
3. I forked "develop" branch (not "typescript")

And now I am making PR to "typescript" with the changes that was made to "develop" branch

I Hope it is OK. 

Real changes by me: 
src/Route/Manager.ts added
src/Route/Manager.js (changed due compilation from .ts)
src/Route/index.ts added
src/Route/index.js (changed due compilation from .ts)
package.json (I added @types/node to devDeps and tweaked standardjs for TS support)
tsconfig.json added

Sorry for bit mess (not in the code though, only in PR). Please direct me if I am doing something wrong.

### CODE REVIEW

**Comment by RomainLanz** [comment]
Hey @anurbol ! 👋 

You can rebase your branch against the correct one to avoid having those type of PR.

**Comment by anurbol** [comment]
@RomainLanz Oh thanks! I've read something about that, but not sure how to properly do it, can you give me 
more detailed instructions on which commands, in which order I should execute in this type of scenario, please?

**Comment by RomainLanz** [comment]
There's a [lot of documentation](https://help.github.com/articles/syncing-a-fork/) about how to keep a fork updated.

**Comment by anurbol** [comment]
@RomainLanz I needed that link! Thanks! I ll rework this PR

**Comment by anurbol** [comment]
@RomainLanz Wow, great! Good that you told me this now, because I've edited just few files (that I listed above) so far. We should have information about each others work in future, by announcing it anywhere. Or maybe I've missed it, don't know where that information could be.

Can you tell me please, I guess after your changes there will be TS support in controllers, am I right? But there will not be support for it in models? Because models are handled by Lucid.

**Pull request closed without merging**
