### PR TITLE
Add app base url for view global helpers

### PR DESCRIPTION
**Pull request by jmlaya**

### CODE REVIEW

**Comment by RomainLanz** [comment]
Hey @jmlaya! 👋 

There's a lot of change that isn't related to this PR in your commit (your linter has probably done some job).
Please, clean them to only have what you changed.

**Comment by jmlaya** [comment]
@RomainLanz I'm sorry, yes the linter done that job. The PR is clean and ready for review.

**Comment by RomainLanz** [comment]
Cool !

I like the idea, what do you think @thetutlage ?

**Comment by webdevian** [comment]
This makes sense 👍

**Comment by thetutlage** [comment]
1. What happens when there is no base URL defined?
2. Also what if I don't want absolute URL's or maybe how absolute URL's helps over relative one's ?

**Comment by jmlaya** [comment]
@thetutlage @RomainLanz Thanks for your review.

The reason for this improvement it's really simple. I'm implementing an application with this framework but the root path is not the base URL of the host, for example, `http://localhost/myapp`. The view helpers fail in this context.

The idea is that you can to define the base path of the URL, could be absolute or relative because just it's added to prepend the URL provided to the helper.

Both samples will work fine
```
baseUrl: http://anotherdomain.com
baseUrl: /my-base-segment
```

**Comment by jmlaya** [comment]
Hi, @thetutlage @RomainLanz What's the next step?, I have another pull request related

**Comment by thetutlage** [comment]
Hi, can you please open a PR for docs too?

**Pull request merged**
