### PR TITLE
Encryption fails on longer content

### PR DESCRIPTION
**Pull request by r15ch13**
Using encryption like it's shown in the third example: https://nodejs.org/api/crypto.html#crypto_class_cipher

### CODE REVIEW

**Comment by r15ch13** [comment]
Hm i think your test suite has a problem. Running `mocha test\unit\encryption.spec.js` works.

**Comment by thetutlage** [comment]
Test suite does not have a problem, run `npm run standard` to make sure your files does not have linting errors

**Comment by r15ch13** [comment]
https://travis-ci.org/adonisjs/adonis-framework/jobs/114226669
`/home/travis/build/adonisjs/adonis-framework/src/View/extensions.js:52:17: Missing space after *.`
Didn't touch that file :)

**Comment by thetutlage** [comment]
Weird, it should have failed earlier, will fix it

**Comment by thetutlage** [comment]
Fixed in https://github.com/adonisjs/adonis-framework/commit/3095839f7e52447f04ec09c49154ade523955c49.

Also i can see you have two open PR's, can you close the one which is irrelevant according to you?

**Comment by thetutlage** [comment]
Closed in favor of #113

**Pull request closed without merging**
