### PR TITLE
chore: upgrade install-pkg

### PR DESCRIPTION
**Pull request by benmccann**
### ❓ Type of change

- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

Upgrades a dependency to the latest version

I tried to upgrade in https://github.com/adonisjs/core/pull/4703, but ran into a regression. I fixed that in `install-pkg` and it has been released as 0.4.1

### 📝 Checklist

- [ ] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by thetutlage** [comment]
Hey @benmccann 

Thanks for working across all these dependencies and providing a fix. But it seems like the tests are still failing. I dig into the logs of the failing tests and this is how it looks like.

**With the recent version of `install-pkg`**
CleanShot 2024-08-27 at 10 37 55@2x

Here you can see that we receive a success message that pnpm has installed a non-existing package successfully. 

**With version `0.3.3`**
CleanShot 2024-08-27 at 10 38 49@2x

**Comment by benmccann** [comment]
Hmm. That's essentially what it was doing before and has been fixed. Is there a lockfile that needs to be updated for it to use the new version of `install-pkg` or anything that might be caching the old package version?

I just verified in a test project that it works as expected:
```
$ node test.js
npm error code E404
npm error 404 Not Found - GET https://registry.npmjs.org/inexistant - Not found
npm error 404
npm error 404  'inexistant@*' is not in this registry.
npm error 404
npm error 404 Note that you can also install from a
npm error 404 tarball, folder, http url, or git url.
node_modules/tinyexec/dist/main.js:529
      throw new x(this, s);
            ^

x [Error]: Process exited with non-zero status (1)
```

**Comment by thetutlage** [comment]
Did you use the `pnpm` package manager in your test setup?

**Comment by benmccann** [comment]
Thanks. I hadn't, but I just tested and pnpm is also working correctly:
```
 ERR_PNPM_FETCH_404  GET https://registry.npmjs.org/inexistant: Not Found - 404

inexistant is not in the npm registry, or you have no permission to fetch it.

An authorization header was used: Bearer npm_[hidden]
Progress: resolved 2, reused 2, downloaded 0, added 0
node_modules/.pnpm/tinyexec@0.3.0/node_modules/tinyexec/dist/main.js:529
      throw new x(this, s);
```

**Comment by benmccann** [comment]
> I dig into the logs of the failing tests and this is how it looks like.

You must have somehow been testing with `@antfu/install-pkg` 0.4.0. Version 0.4.1 does indeed throw an exception. It just has a slightly different error message than before and so the assertion for the error message needed to be updated. I've done that and that test is now passing

There's still one more failing test I haven't had a chance to look at though

**Comment by benmccann** [comment]
Oh, the other test error happens on `develop` without this PR and is unrelated

This PR should be good to go now!

**Comment by thetutlage** [comment]
Cool. That seems to work. Thanks for taking out the time to work on it.

Side note: I wish the quality of logs should have been same as with the earlier versions. Showing `"Process exited with non-zero status (1)"` is far less helpful than `"inexistant is not in the npm registry, or you have no permission to fetch it"`

**Comment by benmccann** [comment]
> Side note: I wish the quality of logs should have been same as with the earlier versions. Showing "Process exited with non-zero status (1)" is far less helpful than "inexistant is not in the npm registry, or you have no permission to fetch it"

I don't think the logs have changed that much. I believe the "Process exited with non-zero status" previously said "pnpm install inexistant exited with status 1". It probably was a little more informative before, but I'm not sure it was drastically different

That change, btw, came from `execa` being replaced by `tinyexec` in the dependency tree, which is much smaller. But it could be a feature request to `tinyexec` to update the error message to be slightly more informative and align with what `execa` did

**Comment by thetutlage** [comment]
@benmccann Yeah, I agree the behavior is same and comment was just nitpicking a small thing 😀

**Pull request merged**
